name: Django Runserver Check

on:
  push:
    branches: [ main ]

jobs:
  runserver-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: python manage.py migrate

    - name: Start Django runserver in background
      run: |
        python manage.py runserver 0.0.0.0:8000 &
        echo $! > runserver_pid.txt
        sleep 10  # wait for server to start

    - name: Check if Django site responds
      run: |
        curl --fail http://127.0.0.1:8000 || (cat runserver_pid.txt | xargs kill && exit 1)

    - name: Stop server
      run: |
        cat runserver_pid.txt | xargs kill
